---
version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/cli-plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            - node-modules-
      - run: yarn
      - run: ./node_modules/.bin/jest --coverage && bash <(curl -s https://codecov.io/bash)
      - run: ./node_modules/.bin/flow check
      - run: ./node_modules/.bin/eslint .
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - /usr/local/share/.cache/yarn
